const nodemailer = require('nodemailer');

const sendAppointmentEmail = async (data) => {
    // Check if credentials exist
    if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
        console.log('Skipping Email (Missing EMAIL_USER or EMAIL_PASS in .env)');
        return;
    }

    const transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
            user: (process.env.EMAIL_USER || "").trim(),
            pass: (process.env.EMAIL_PASS || "").trim().replace(/^"|"$/g, '')
        }
    });

    const { name, phone, email, treatment, date, time, message, urgency } = data;

    // Email content for Admin
    const mailOptions = {
        from: process.env.EMAIL_USER,
        to: process.env.ADMIN_EMAIL || process.env.EMAIL_USER,
        subject: `New Appointment Request - ${name}`,
        html: `
            <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 25px; border: 1px solid #e2e8f0; border-radius: 16px; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);">
                <h2 style="color: #2563eb; margin-bottom: 20px; text-align: center;">New Appointment Request</h2>
                <div style="background: #f8fafc; padding: 20px; border-radius: 12px;">
                    <table style="width: 100%; border-collapse: separate; border-spacing: 0 10px;">
                        <tr>
                            <td style="font-weight: bold; color: #64748b; width: 40%;">Patient Name</td>
                            <td style="color: #1e293b;">${name}</td>
                        </tr>
                        <tr>
                            <td style="font-weight: bold; color: #64748b;">Phone No</td>
                            <td style="color: #1e293b;"><a href="tel:${phone}" style="color: #2563eb; text-decoration: none;">${phone}</a></td>
                        </tr>
                        <tr>
                            <td style="font-weight: bold; color: #64748b;">Email</td>
                            <td style="color: #1e293b;">${email || 'Not provided'}</td>
                        </tr>
                        <tr>
                            <td style="font-weight: bold; color: #64748b;">Treatment</td>
                            <td style="background: #dcfce7; color: #166534; padding: 4px 12px; border-radius: 9999px; font-size: 13px; font-weight: bold;">${treatment}</td>
                        </tr>
                        <tr>
                            <td style="font-weight: bold; color: #64748b;">Date & Time</td>
                            <td style="color: #1e293b;">${date} at ${time}</td>
                        </tr>
                        <tr>
                            <td style="font-weight: bold; color: #64748b;">Urgency</td>
                            <td style="${urgency === 'emergency' ? 'color: #ef4444; font-weight: bold;' : 'color: #1e293b;'}">${urgency.toUpperCase()}</td>
                        </tr>
                        <tr>
                            <td style="font-weight: bold; color: #64748b; vertical-align: top;">Message</td>
                            <td style="color: #1e293b; line-height: 1.5;">${message || 'N/A'}</td>
                        </tr>
                    </table>
                </div>
                
                <div style="margin-top: 25px; text-align: center; color: #94a3b8; font-size: 13px; border-top: 1px solid #f1f5f9; pt: 20px;">
                    <p>Generated by Dent O Care Website Portal</p>
                </div>
            </div>
        `
    };

    try {
        await transporter.sendMail(mailOptions);
        console.log(`Notification email sent to ${mailOptions.to}`);
    } catch (error) {
        console.error('Email Sending Error:', error);
        throw error;
    }
};

module.exports = sendAppointmentEmail;
